[package]
name = "evdev-sys"
version = "0.1.0"
authors = ["Nayan Deshmukh <nayan26deshmukh@gmail.com"]
build = "build.rs"
license = "MIT/Apache-2.0"
keywords = ["evdev"]
links = "evdev"
repository = "https://github.com/ndesh26/evdev-rs"
description = """
Raw bindings to libevdev

High level Rust bindings are available in the `evdev` crate
"""

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
cc = "1.0"
