[package]
name = "evdev-sys"
version = "0.2.6"
authors = ["Nayan Deshmukh <nayan26deshmukh@gmail.com"]
build = "build.rs"
license = "MIT/Apache-2.0"
keywords = ["evdev"]
links = "evdev"
repository = "https://github.com/ndesh26/evdev-rs"
edition = "2018"
description = """
Raw bindings to libevdev

High level Rust bindings are available in the `evdev` crate
"""

[features]
v1_10 = []

[dependencies]
libc = "0.2.67"

[build-dependencies]
system-deps = "7"

[package.metadata.system-deps.libevdev]
name = "libevdev"
version = "1"

[package.metadata.system-deps.libevdev.v1_10]
version = "1.10"
